remove modal for user commonality
aopell/SchoologyPlus pull request #200
Opened 2020-09-21 04:59 UTC by reteps

Courses in Common now automatically load below the users name!
![image](https://user-images.githubusercontent.com/13869303/93734014-9ec35b00-fba5-11ea-9c2a-8f0f7418b025.png)

2020-09-21 05:20 UTC, atomicproton commented on js/user.js
> +    const userID = document.location.href.match(/\/(\d+)\//)[1]
I'd end each statement with a semicolon just to match the style of the rest of the code. 

Also in my experience I've run in to many strange bugs when dealing with semicolon auto-insertion.

2020-09-21 05:23 UTC, aopell requested changes
Yes, please add semicolons!

2020-09-21 05:25 UTC, reteps commented
Alright! I have not experienced that issue before, but I added them in.

2020-09-21 05:39 UTC, reteps commented
1 More change, now click on the gradeText to edit instead of the icon.

2020-09-21 05:56 UTC, glen3b commented
Disclaimer: I haven't looked at the code and I'm not currently in a position to test it.

Marking here some things we'll want to verify and/or address:
- Sometimes profiles aren't blank. I think a permissions thing on the LAUSD instance makes them so. We'll want to make sure your change doesn't cause unexpected behavior either with non-blank profiles or on the user's own profile.
- If you can keep one change per PR that would be appreciated. Please move the gradeText change to another PR if you can. (We can handle keeping the commit history clean when it comes to that.)

From a design perspective I'm definitely not opposed to inlining the courses in common on profile pages, assuming there's not a large performance impact. Thanks for taking a look at this!

2020-09-21 14:19 UTC, reteps commented
This does work with non-blank profiles, e.g. my own profile.
![image](https://user-images.githubusercontent.com/13869303/93778478-f5f01c80-fbf3-11ea-9cb1-b268de16590a.png)

2020-09-21 14:31 UTC, reteps commented
Grade text has been moved to a seperature pull request.

2020-09-22 00:11 UTC, glen3b requested changes
Thanks again for looking at this. There's a couple small changes I'd like to see addressed. The one thing I didn't point out there is that I'm currently having functionality issues when I pull this up on my own profile on the main schoology.com instance, and I'm not currently in a position to troubleshoot that.

Other than that, looks like a nice change! As a recommendation, for future changes, I've found when making PRs, keeping your `develop` branch clean and up-to-date with ours, and forking off your `develop` branch into feature branches on your own repository for making PRs helps avoid PR cross-contamination and makes including upstream changes simple.

2020-09-22 00:11 UTC, glen3b commented on js/user.js
>  })();
I think for anonymous async functions like this one we like to have an error handler or some other way to make sure exceptions don't get swallowed. I believe grades.js has one if you want to model off of it. In lieu of a larger refactoring, simply logging the error should be fine.

2020-09-22 00:11 UTC, glen3b commented on js/user.js
> +    const title = createElement("h4", [], {textContent: "Courses In Common"});
Stylistically, can we make this closer to a "proper" section? See this screenshot (Firefox):
![image](https://user-images.githubusercontent.com/3952667/93833058-674bc180-fc2c-11ea-9e19-34b68d66f419.png)
Can we have "Courses In Common" be closer stylistically to "About Me" or "Contact Information"?

2020-09-22 01:30 UTC, reteps commented
closing, I can't figure out reverting this correctly so I am redoing this.

2020-09-22 01:30 UTC, closed without merging